#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments


# Libraries twoPhaseSystem, interfacialModels and phaseCompressibleTurbulenceModels
# are circularly dependent on each other, so we need to compile in stages.

wmake lib twoPhaseSystem
wmake lib interfacialModels
wmake lib phaseCompressibleTurbulenceModels

wmake $targetType twoPhaseSystem
wmake $targetType interfacialModels
wmake $targetType phaseCompressibleTurbulenceModels

rm -f $FOAM_LIBBIN/libcompressibleTwoPhaseSystem.dll $FOAM_LIBBIN/libcompressibleTwoPhaseSystem.so \
      && wmake $targetType twoPhaseSystem
rm -f $FOAM_LIBBIN/libcompressibleEulerianInterfacialModels.dll $FOAM_LIBBIN/libcompressibleEulerianInterfacialModels.so \
      && wmake $targetType interfacialModels
rm -f $FOAM_LIBBIN/libphaseCompressibleTurbulenceModels.dll $FOAM_LIBBIN/libphaseCompressibleTurbulenceModels.so \
      && wmake $targetType phaseCompressibleTurbulenceModels

wmake $targetType

#------------------------------------------------------------------------------
