#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Libraries multiphaseSystem and multiphaseCompressibleTurbulenceModels
# are circularly dependent on each other, we need to compiler in stages.

wmake lib multiphaseSystem
wmake lib multiphaseCompressibleTurbulenceModels

wmake $targetType multiphaseSystem
wmake $targetType multiphaseCompressibleTurbulenceModels

wmake $targetType

#------------------------------------------------------------------------------
